#!/usr/bin/env perl

use warnings;
use strict;

my $contents;
{
  local $/ = undef;

  open my $fh, '<', $ARGV[0] or die $!;
  $contents = <$fh>;
  close $fh;
}

$contents =~ s/\r\n/\n/g;

{
  open my $fh, '>', $ARGV[1] or die $!;
  print $fh $contents;
  close $fh;
}

exit 0;
